name: 'No-Op on Release'

on:
  workflow_dispatch:

jobs:
  noop-job:
    name: 'Do Nothing on Release'
    runs-on: ubuntu-latest

    steps:
      - name: 'No Operation'
        run: echo "This job does nothing on release."
